### ISSUE TITLE
It seems that it stoped working Google Maps → Geoportal

### ISSUE THREAD

**Issue by pawelkontek** [ptomaszek/geoportalgovpl-to-googlemaps#2]
It seems that it stoped working Google Maps → Geoportal:

<img width="1031" alt="image" src="https://github.com/ptomaszek/geoportalgovpl-to-googlemaps/assets/7879784/d87612f7-7cc9-4bc8-88bf-aa850619207f">

**Comment by ptomaszek** [comment]
Hi,

I fixed the bug locally but didn't release it yet. Hope to do it next week for both FF and Chrome.

Thanks for reporting

**Comment by pawelkontek** [comment]
Thanks! I look forward to the update. It is a daily life-saver! <3 
Thank you for your amazing work!

**Comment by ptomaszek** [comment]
Nice to hear such feedback!

Extension should now work in Chrome. If it doesn't, please ensure it's been updated to version 2.2.0:
1. Visit [chrome://extensions/](chrome://extensions/)
3. If you see old version, click Update ![image](https://github.com/ptomaszek/geoportalgovpl-to-googlemaps/assets/5464274/cd903249-83a9-4b95-9485-bde06e96c77d)

---

I'm having problems with my Firefox account, so cannot update the extension there. Let me keep this issue open until I fix that too

**Comment by pawelkontek** [comment]
Thanks a lot! It works great in Chrome. I don't have Firefox to test it.
Thank you!
